# TODO: this should be auto generated by a script

load("//private/remote:temurin_archive.bzl", "temurin_archive")

JAVA_RELEASE_VERSIONS = {
    "temurin21_jre_amd64": "21.0.2",
    "temurin21_jdk_amd64": "21.0.2",
    "temurin21_jre_arm64": "21.0.2",
    "temurin21_jdk_arm64": "21.0.2",
    "temurin21_jre_ppc64le": "21.0.2",
    "temurin21_jdk_ppc64le": "21.0.2",
    "temurin22_jre_amd64": "22",
    "temurin22_jdk_amd64": "22",
    "temurin22_jre_arm64": "22",
    "temurin22_jdk_arm64": "22",
    "temurin22_jre_ppc64le": "22",
    "temurin22_jdk_ppc64le": "22",
}

def repositories():
    temurin_archive(
        name = "temurin21_jre_amd64",
        sha256 = "51141204fe01a9f9dd74eab621d5eca7511eac67315c9975dbde5f2625bdca55",
        strip_prefix = "jdk-21.0.2+13-jre",
        urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jre_x64_linux_hotspot_21.0.2_13.tar.gz"],
        version = "21.0.2+13",
        architecture = "amd64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin21_jdk_amd64",
        sha256 = "454bebb2c9fe48d981341461ffb6bf1017c7b7c6e15c6b0c29b959194ba3aaa5",
        strip_prefix = "jdk-21.0.2+13",
        urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz"],
        version = "21.0.2+13",
        architecture = "amd64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin21_jre_arm64",
        sha256 = "64c78854184c92a4da5cda571c8e357043bfaf03a03434eef58550cc3410d8a4",
        strip_prefix = "jdk-21.0.2+13-jre",
        urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jre_aarch64_linux_hotspot_21.0.2_13.tar.gz"],
        version = "21.0.2+13",
        architecture = "arm64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin21_jdk_arm64",
        sha256 = "3ce6a2b357e2ef45fd6b53d6587aa05bfec7771e7fb982f2c964f6b771b7526a",
        strip_prefix = "jdk-21.0.2+13",
        urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.2_13.tar.gz"],
        version = "21.0.2+13",
        architecture = "arm64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin21_jre_ppc64le",
        sha256 = "caaf48e50787b80b810dc08ee91bd4ffe0d0696bd14906a92f05bf8c14aabb22",
        strip_prefix = "jdk-21.0.2+13-jre",
        urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jre_ppc64le_linux_hotspot_21.0.2_13.tar.gz"],
        version = "21.0.2+13",
        architecture = "ppc64le",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin21_jdk_ppc64le",
        sha256 = "d08de863499d8851811c893e8915828f2cd8eb67ed9e29432a6b4e222d80a12f",
        strip_prefix = "jdk-21.0.2+13",
        urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2%2B13/OpenJDK21U-jdk_ppc64le_linux_hotspot_21.0.2_13.tar.gz"],
        version = "21.0.2+13",
        architecture = "ppc64le",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin22_jre_amd64",
        sha256 = "faceda94ffd16e177cb674471f29789e48378f9f190eac8523713a0cb3324be9",
        strip_prefix = "jdk-22+36-jre",
        urls = ["https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/OpenJDK22U-jre_x64_linux_hotspot_22_36.tar.gz"],
        version = "22+36",
        architecture = "amd64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin22_jdk_amd64",
        sha256 = "bc3d99e816d0c373f424cd7aa2b6d3e8081a7189fe55c1561616922200ec8e47",
        strip_prefix = "jdk-22+36",
        urls = ["https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/OpenJDK22U-jdk_x64_linux_hotspot_22_36.tar.gz"],
        version = "22+36",
        architecture = "amd64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin22_jre_arm64",
        sha256 = "4748e5024eb0251ddf0f576e4c56d21270b1f2186f62b25fc1d89c888d742ed4",
        strip_prefix = "jdk-22+36-jre",
        urls = ["https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/OpenJDK22U-jre_aarch64_linux_hotspot_22_36.tar.gz"],
        version = "22+36",
        architecture = "arm64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin22_jdk_arm64",
        sha256 = "4b52670caea44848cee893e35c804380817b6eff166cf64ee70ca2bfaac3d1c7",
        strip_prefix = "jdk-22+36",
        urls = ["https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/OpenJDK22U-jdk_aarch64_linux_hotspot_22_36.tar.gz"],
        version = "22+36",
        architecture = "arm64",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin22_jre_ppc64le",
        sha256 = "e1cce04600b388777a1a278dda572a664db14cea034dc131155b3da5e6e885e5",
        strip_prefix = "jdk-22+36-jre",
        urls = ["https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/OpenJDK22U-jre_ppc64le_linux_hotspot_22_36.tar.gz"],
        version = "22+36",
        architecture = "ppc64le",
        control = "//java:control",
    )

    temurin_archive(
        name = "temurin22_jdk_ppc64le",
        sha256 = "8c062e934d95c639f97b4e51b968eed694a6653248727c3db8bc5e0e55cfd7f4",
        strip_prefix = "jdk-22+36",
        urls = ["https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/OpenJDK22U-jdk_ppc64le_linux_hotspot_22_36.tar.gz"],
        version = "22+36",
        architecture = "ppc64le",
        control = "//java:control",
    )
